import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { HeaderComponent } from "@/shared/components/Header.component";
import { SidebarComponent } from "@/shared/components/Sidebar.component";
import { FollowsComponent } from "@/shared/components/Follows.component";

export const metadata: Metadata = {
  title: "Frige",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="light" lang="en">
      <Toaster position="top-center" />
      <body>
        <HeaderComponent />
        <main className="h-[92vh] flex">
          <SidebarComponent />
          <section className="flex w-5/6 h-fit p-8 gap-5 bg-gray-100">
            <div className="border border-gray-200 w-5/6 rounded-sm bg-white flex justify-center h-fit min-h-full">
              {children}
            </div>
            <FollowsComponent />
          </section>
        </main>
      </body>
    </html>
  );
}
