import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="light" lang="en">
      <Toaster position="top-center" />
      <body className="border">
        <header className="bg-white h-[100px] border border-gray-300">
          <div className="border border-gray-300"></div>
          <div className="border border-gray-300"></div>
        </header>
        {children}
      </body>
    </html>
  );
}
